# Generated by Django 4.2.2 on 2023-08-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
